name: Notify Discord on Deployment

on:
  deployment_status:

jobs:
  notify-success:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Send Success Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"embeds\": [{\"description\": \"✅ **[تم تحديث إحصائيات السيرفر بنجاح](https://Hussain96o.github.io/Server-Analytics-/)**\", \"color\": 3066993}]}" \
          $DISCORD_WEBHOOK
